name: Deploy

#on:
#  pull_request:
#   push:
 #   branches:
 #     - main

jobs:
  deploy:      
    runs-on: ubuntu-latest
    
    steps:
    - name: Install Salesforce CLI
      run: |
       wget https://developer.salesforce.com/media/salesforce-cli/sfdx-cli/channels/stable/sfdx-cli-v7.72.0-697e9faee2-linux-x64.tar.xz
       mkdir sfdx-cli
       tar xJf sfdx-cli-v7.72.0-697e9faee2-linux-x64.tar.xz -C sfdx-cli --strip-components 1
       ./sfdx-cli/install
    - name: Checkout dev branch and grab environment keys
      uses: actions/checkout@v2
      with:
        ref: 'dev'
        path: env
    - name: Checkout source code
      uses: actions/checkout@v2
      with:
        path: main
    - name: Set environment variable
      run: |
        cat ./env/.github/workflows/env | grep QA_CONSUMER_KEY= | grep -o '".*"' | sed 's/"//g' > ./main/QA_CONSUMER_KEY
        cat ./env/.github/workflows/env | grep QA_USERNAME= | grep -o '".*"' | sed 's/"//g' > ./main/QA_USERNAME
    - name: Authenticate Sandbox
      run: |
        echo "${SALESFORCE_JWT_SECRET_KEY}" > server.key
        cat server.key
        cat ./main/QA_CONSUMER_KEY
        cat ./main/QA_USERNAME
        sfdx force:auth:jwt:grant --jwtkeyfile ./server.key --setalias qaorg --instanceurl https://login.salesforce.com --clientid $(cat ./main/QA_CONSUMER_KEY) --username $(cat ./main/QA_USERNAME)
     #  sfdx force:auth:jwt:grant --jwtkeyfile ./server.key --setalias qaorg --instanceurl https://test.salesforce.com --clientid 3MVG9bhkrN.tsmW_4B6qdyXrf7zLvgLz3GejpQpqG.X46L0fl4muv36x_IntYAixLXXR2F_1uyw== --username shprot34@resourceful-bear-jseaq.com --setdefaultusername
       
     #    sfdx force:auth:jwt:grant --clientid 3MVG9JEx.BE6yifP0uECQu_R_i2GGcTWMixpfXv8ZrU2_DRB84aXlDr9BPZ3OIVzH9YkwJSkUX8kH8bwW6Jh6 \
     #     --jwtkeyfile ./SFDX_JWT_SECRET.key \
     #     --username 	integrationuser@cloverhealth.com.dce \
     #     --setdefaultusername
      env:
        SALESFORCE_JWT_SECRET_KEY: ${{ secrets.SFDX_JWT_SECRET }}
    - name: Deploy code to Target Sandbox
      run: |
          cd ./main
          ls
          sfdx force:source:deploy --wait 180 -u qaorg --manifest manifest/package.xml --verbose
