name: Deploy

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged

    steps:
      - name: checkout
        if: github.event.pull_request.merged
        uses: actions/checkout@v1

    
  deploy:      
    runs-on: ubuntu-latest
    needs: validate
    
    steps:
    - name: deploy to prod
      run: echo deployment complete
      
    - name: Install Salesforce CLI
      run: |
       wget https://developer.salesforce.com/media/salesforce-cli/sfdx-cli/channels/stable/sfdx-cli-v7.72.0-697e9faee2-linux-x64.tar.xz
       mkdir sfdx-cli
       tar xJf sfdx-cli-v7.72.0-697e9faee2-linux-x64.tar.xz -C sfdx-cli --strip-components 1
       ./sfdx-cli/install
     
